<html>
  <head>
    <meta property="og:title" content="GiggleVerify" />
    <meta property="og:site_name" content="thegigler.com" />
    <meta property="og:url" content="https://www.thegigler.com/GiggleVerify" />
    <meta property="og:image" content="https://www.thegigler.com/GiggleVerify/images/giggleverify-thumb.jpg" />
    <meta property="og:image:width" content="438" />
    <meta property="og:image:height" content="404" />
    <link rel="shortcut icon" href="images/giggleverify.ico"/>
    <link rel=stylesheet type=text/css href="styles.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="giggleverify.js"></script>
    <title>GiggleMe</title>
  </head>
  <body>
    <div class="hero-image">
      <div class="hero-text">
      </div>
    </div>
